{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monize-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monize.frontend.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - {{ include "monize.hostname" . }}
  rules:
    - backendRefs:
        - kind: Service
          name: monize-frontend-service
          namespace: {{ .Values.global.namespace }}
          port: {{ .Values.frontend.service.port }}
{{- end }}
