apiVersion: v1
kind: Service
metadata:
  name: monize-backend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monize.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "monize.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.service.port }}
      protocol: TCP
      appProtocol: http
      targetPort: http
      name: web
