apiVersion: v1
kind: Service
metadata:
  name: monize-frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monize.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "monize.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      protocol: TCP
      appProtocol: http
      targetPort: http
      name: web
