apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monize-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monize.backend.labels" . | nindent 4 }}
    {{- with .Values.backend.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: monize-backend
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.backend.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "monize.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "monize.backend.labels" . | nindent 8 }}
        {{- with .Values.backend.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      restartPolicy: Always
      automountServiceAccountToken: false
      affinity: null
      containers:
        - name: monize-backend
          image: "{{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          {{- with .Values.backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            {{- with .Values.backend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: env-vars-backend
            {{- with .Values.backend.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: http
              protocol: TCP
          {{- with .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
